# Databricks notebook source
# MAGIC %md 
# MAGIC <img src="../../docs/flow_a.png" width="560" height="275">
# MAGIC
# MAGIC ### Databricks demo setup script for ingesting MDF4 telemetry data.
# MAGIC  
# MAGIC * Creates or resets Unity Catalog objects (catalog, schema, volumes) and a minimal `status` table
# MAGIC * **Demo mode** (`use_demo_data=True`): optional full schema reset and OBD zip → MDF4 staging
# MAGIC * **Live mode** (`use_demo_data=False`): never drops schema/tables; only `CREATE IF NOT EXISTS`; no demo import
# MAGIC * Exposes widgets to parameterize catalog/schema/volumes and processing parameters

# COMMAND ----------

# MAGIC %run ./bundle_bootstrap

# COMMAND ----------

import os

import utils
from utils import schema_definitions
from utils.constants import DELTA_TARGET_FILE_SIZE_BYTES
from utils.notebook_helpers import is_uc_volume_path, notebook_dir, resolve_volume_path

_nb_dir = notebook_dir(dbutils)

# COMMAND ----------

# DBTITLE 1,Define widgets
dbutils.widgets.dropdown("reset", "False", ["True", "False"], "reset all tables (demo only)")
dbutils.widgets.text("catalog", "mda_demo")
dbutils.widgets.text("schema", "default")
dbutils.widgets.text("demo_data_path", "../../examples/obd_dataset")
dbutils.widgets.text("mdf4_volume", "mdf4")
dbutils.widgets.text("checkpoint_volume", "mdf4_checkpoint")
dbutils.widgets.text("max_batch_size", "100")
dbutils.widgets.dropdown("use_demo_data", "True", ["True", "False"], "demo vs live (no deletes in live)")

# COMMAND ----------

# Resolve widget values and cast numeric parameters
reset_requested = dbutils.widgets.get("reset").lower() == 'true'
catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
demo_data_path_widget = dbutils.widgets.get("demo_data_path")
if demo_data_path_widget in ("", "../../examples/obd_dataset"):
  demo_data_path = os.path.normpath(f"/Workspace{_nb_dir}/../../examples/obd_dataset")
else:
  demo_data_path = demo_data_path_widget
mdf4_volume = dbutils.widgets.get("mdf4_volume")
checkpoint_volume = dbutils.widgets.get("checkpoint_volume")
max_batch_size = int(dbutils.widgets.get("max_batch_size"))
use_demo_data = dbutils.widgets.get("use_demo_data").lower() == 'true'

try:
  status_exists = utils.table_exists(spark, catalog, schema, 'status')
except Exception:
  # Catalog or information_schema not reachable yet (e.g. first provision)
  status_exists = False

if use_demo_data:
  # Demo: allow full reset on first run or when requested
  reset = reset_requested or not status_exists
else:
  # Live: never drop data; reset widget is ignored for destructive actions
  reset = False
  if reset_requested:
    print("Live mode (use_demo_data=False): 'reset' is ignored; no schema or table drops are performed.")

# COMMAND ----------

# Bootstrap catalog, schema, volumes, and base tables.
# Destructive reset (DROP SCHEMA) runs only in demo mode when reset is True.
if use_demo_data and reset:
  print("resetting demo")
  spark.sql(f"DROP SCHEMA IF EXISTS {catalog}.{schema} CASCADE")

try:
  spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
except Exception as e:
  print(f"Error creating catalog {catalog}: {e}")

spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{schema}")
if not is_uc_volume_path(mdf4_volume):
  spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.{schema}.{mdf4_volume}")
if not is_uc_volume_path(checkpoint_volume):
  spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.{schema}.{checkpoint_volume}")
spark.sql(
  f"CREATE TABLE IF NOT EXISTS {catalog}.{schema}.status "
  "(container_id BIGINT GENERATED BY DEFAULT AS IDENTITY, run_id STRING, filename STRING, status STRING, "
  "_load_ts TIMESTAMP, _processing_done_ts TIMESTAMP)"
)

# COMMAND ----------

# DBTITLE 1,Create ingest target tables on demo reset
if use_demo_data and reset:
  empty_channels = spark.createDataFrame([], schema_definitions.CHANNELS_SCHEMA)
  empty_meta = spark.createDataFrame([], schema_definitions.BRONZE_META_SCHEMA)
  empty_masters = spark.createDataFrame([], schema_definitions.MASTERS_SCHEMA)
  empty_channel_tags = spark.createDataFrame([], schema_definitions.TAGS_SCHEMA)
  empty_channel_metrics = spark.createDataFrame([], schema_definitions.CHANNEL_METRICS_SCHEMA)
  empty_container_tags = spark.createDataFrame([], schema_definitions.CONTAINER_TAGS_SCHEMA)
  empty_container_metrics = spark.createDataFrame([], schema_definitions.METRICS_SCHEMA)

  table_specs = [
      ("channels", empty_channels, ["container_id", "channel_id"]),
      ("bronze_meta", empty_meta, ["container_id", "channel_id"]),
      ("masters", empty_masters, ["container_id", "group_idx"]),
      ("channel_tags", empty_channel_tags, ["container_id", "channel_id"]),
      ("channel_metrics", empty_channel_metrics, ["container_id", "channel_id"]),
      ("container_tags", empty_container_tags, ["container_id"]),
      ("container_metrics", empty_container_metrics, ["container_id"]),
  ]
  for table_name, empty_df, cluster_cols in table_specs:
    (
        empty_df.write
        .clusterBy(*cluster_cols)
        .format("delta")
        .mode("overwrite")
        .saveAsTable(f"{catalog}.{schema}.{table_name}")
    )
    spark.sql(
        f"ALTER TABLE {catalog}.{schema}.{table_name} "
        f"SET TBLPROPERTIES (delta.targetFileSize = '{DELTA_TARGET_FILE_SIZE_BYTES}')"
    )

# COMMAND ----------

# Stage the demo source from workspace files onto a UC Volume (one-time, idempotent).
# Bundle deploy lands the source at demo_data_path; workspace import auto-extracts
# .zip files, so this typically copies a directory tree verbatim. The volume copy
# is what convert_obd_data consumes.
if use_demo_data:
  mdf_volume_path = resolve_volume_path(catalog, schema, mdf4_volume)
  seed_root = f"{mdf_volume_path}/_seed"
  resolved_demo = utils.prepare_demo_data(
    demo_data_path,
    seed_root,
    dbutils=dbutils,
    notebook_dir=_nb_dir,
  )
  print(f"Using demo data: {resolved_demo}")
  mdf_output_root = f"{mdf_volume_path}/"
  print(f"MF4 output directory: {mdf_output_root} (not under _seed/)")
  utils.convert_obd_data(
    resolved_demo,
    '/tmp/',
    mdf_output_root,
    dbutils,
    force_convert=reset,
  )

# COMMAND ----------

